# Generated by Django 4.2.7 on 2023-11-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_duration', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('start_station_id', models.IntegerField()),
                ('start_station_name', models.CharField(max_length=1000)),
                ('start_station_latitude', models.FloatField()),
                ('start_station_longitude', models.FloatField()),
                ('end_station_id', models.IntegerField(blank=True, null=True)),
                ('end_station_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('end_station_latitude', models.FloatField(blank=True, null=True)),
                ('end_station_longitude', models.FloatField(blank=True, null=True)),
                ('bikeid', models.IntegerField()),
                ('usertype', models.CharField(choices=[('Subscriber', 'Subscriber'), ('Customer', 'Customer')], max_length=100)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Male'), (2, 'Female')])),
            ],
        ),
    ]
